import pandas as pd

def get_companion_profile(plant_name, help_df, avoid_df, ranks_df, comments_df):
    """
    Generates and prints a complete companion planting profile for a given plant.
    """
    plant_name_lower = plant_name.lower() # Standardize input to lowercase

    # Check if the plant exists in our rankings
    if plant_name_lower not in ranks_df['Plant'].str.lower().values:
        print(f"\nSorry, '{plant_name.title()}' was not found in our dataset.")
        return

    print("\n" + "-"*40)
    print(f"Companion Profile for: {plant_name.title()}")
    print("-"*40)

    # --- Find Beneficial Plants (Friends) ---
    friends = help_df[help_df['Source Node'] == plant_name_lower]['Destination Node']
    if friends.empty:
        print(f"✅ No beneficial companions found.")
    else:
        friends_with_ranks = pd.merge(friends.to_frame(), ranks_df, left_on='Destination Node', right_on='Plant')
        top_friends = friends_with_ranks.sort_values(by='Help_Rank', ascending=False).head(5)
        print(f"✅ Top 5 Beneficial Plants:")
        for index, row in top_friends.iterrows():
            print(f"- {row['Plant'].title()}")

    # --- Find Antagonistic Plants (Foes) ---
    foes_part1 = avoid_df[avoid_df['Source Node'] == plant_name_lower]['Destination Node']
    foes_part2 = avoid_df[avoid_df['Destination Node'] == plant_name_lower]['Source Node']
    all_foes = pd.concat([foes_part1, foes_part2], ignore_index=True).unique()
    if len(all_foes) == 0:
         print(f"❌ No antagonistic plants found.")
    else:
        foes_df = pd.DataFrame(all_foes, columns=['Plant'])
        foes_with_ranks = pd.merge(foes_df, ranks_df, on='Plant')
        top_foes = foes_with_ranks.sort_values(by='Avoid_Rank', ascending=False).head(5)
        print(f"\n❌ Top 5 Plants to Avoid:")
        for index, row in top_foes.iterrows():
            print(f"- {row['Plant'].title()}")

    # --- NEW: Find Comments ---
    # Perform a case-insensitive search for the plant name in the comments dataframe
    comment_row = comments_df[comments_df['Common name'].str.lower() == plant_name_lower]
    if not comment_row.empty:
        comment = comment_row.iloc[0]['Comments']
        # Check if a comment exists and is not empty
        if isinstance(comment, str) and comment.strip():
            print(f"\n📝 Comments:")
            print(f"> {comment}") #

def main():
    """
    Main function to load data and run the interactive tool.
    """
    try:
        # Load all the data files generated by analysis.py
        final_ranks = pd.read_csv('final_plant_rankings.csv')
        help_network = pd.read_csv('help_network.csv')
        avoid_network = pd.read_csv('avoid_network.csv')
        # NEW: Load the descriptive veg file for its comments
        veg_data = pd.read_csv('companion_plants_veg.csv')
        print("Companion planting data loaded successfully.")
    except FileNotFoundError as e:
        print(f"Error: Could not find necessary data files like '{e.filename}'.")
        print("Please run the main 'analysis.py' script first to generate these files.")
        return

    # Interactive loop
    while True:
        print("\n" + "="*50)
        plant = input("Enter a plant name for its profile (or type 'exit' to quit): ")
        if plant.lower() in ['exit', 'quit']:
            print("Exiting tool. Goodbye!")
            break
        
        get_companion_profile(plant, help_network, avoid_network, final_ranks, veg_data)

# This makes the script runnable
if __name__ == "__main__":
    main()